import logging

def log_error(e):
    logging.error(f'Error occured: {e}')